import { LanguageCode } from '../types';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  speechCode: string;
  script: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN', script: 'Latin' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN', script: 'Telugu' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN', script: 'Devanagari' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN', script: 'Kannada' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN', script: 'Tamil' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN', script: 'Malayalam' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN', script: 'Bengali' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN', script: 'Gujarati' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN', script: 'Gurmukhi' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechCode: 'or-IN', script: 'Odia' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', speechCode: 'as-IN', script: 'Bengali' },
];

export interface UITranslation {
  appName: string;
  appSubtitle: string;
  navHome: string;
  navAsk: string;
  navGuided: string;
  navRights: string;
  navGrievance: string;
  navKnowledge: string;
  navVoice: string;
  navProfile: string;
  navSettings: string;
  welcomeHero: string;
  heroSubtitle: string;
  askCardTitle: string;
  askCardDesc: string;
  guidedCardTitle: string;
  guidedCardDesc: string;
  grievanceCardTitle: string;
  grievanceCardDesc: string;
  rightsCardTitle: string;
  rightsCardDesc: string;
  voiceCardTitle: string;
  voiceCardDesc: string;
  knowledgeCardTitle: string;
  knowledgeCardDesc: string;
  activeWorkflowNotice: string;
  resumeTaskBtn: string;
  sampleQuestionsLabel: string;
  typePlaceholder: string;
  sendBtn: string;
  voiceBtn: string;
  clearChatBtn: string;
  sourcesLabel: string;
  demoDataBadge: string;
  disclaimerText: string;
  closeBtn: string;
  backBtn: string;
  continueBtn: string;
  cancelBtn: string;
  saveBtn: string;
  editBtn: string;
  downloadPdfBtn: string;
  downloadTxtBtn: string;
  suggestedQ1: string;
  suggestedQ2: string;
  suggestedQ3: string;
  suggestedQ4: string;
  voiceListening: string;
  voiceProcessing: string;
  voiceSpeaking: string;
  voiceIdle: string;
}

export const TRANSLATIONS: Record<LanguageCode, UITranslation> = {
  en: {
    appName: 'Co-opSahayak',
    appSubtitle: 'AI-Powered Cooperative & Legal Helpdesk',
    navHome: 'Home',
    navAsk: 'Ask Assistant',
    navGuided: 'Guided Tasks',
    navRights: 'My Rights',
    navGrievance: 'File a Grievance',
    navKnowledge: 'Knowledge & Sources',
    navVoice: 'Voice Assistant',
    navProfile: 'My Profile',
    navSettings: 'Settings',
    welcomeHero: 'How can we help with your cooperative today?',
    heroSubtitle: 'Understand governance rules, member rights, elections, procedures, and draft official grievances with grounded cooperative bylaws.',
    askCardTitle: 'Ask a Question',
    askCardDesc: 'Get clear answers on laws, bylaws, rights, and voting rules.',
    guidedCardTitle: 'Guided Tasks',
    guidedCardDesc: 'Complete common cooperative procedures step-by-step.',
    grievanceCardTitle: 'File a Grievance',
    grievanceCardDesc: 'Prepare and document a structured formal grievance letter.',
    rightsCardTitle: 'My Rights',
    rightsCardDesc: 'Explore your statutory rights & governance responsibilities.',
    voiceCardTitle: 'Voice Assistant',
    voiceCardDesc: 'Speak naturally in your preferred regional language.',
    knowledgeCardTitle: 'Knowledge & Sources',
    knowledgeCardDesc: 'Inspect the bylaws, acts, and rules powering this assistant.',
    activeWorkflowNotice: 'You have an active in-progress task',
    resumeTaskBtn: 'Resume Task',
    sampleQuestionsLabel: 'Frequently Asked Cooperative Questions:',
    typePlaceholder: 'Ask in your language (e.g. Can I vote in cooperative election?)...',
    sendBtn: 'Send Query',
    voiceBtn: 'Voice Input',
    clearChatBtn: 'Clear Chat',
    sourcesLabel: 'Verified Sources & Citations',
    demoDataBadge: 'DEMO KNOWLEDGE BASE',
    disclaimerText: 'Notice: This assistant provides grounded informational guidance based on cooperative bylaws and acts. It does not replace official legal counsel.',
    closeBtn: 'Close',
    backBtn: 'Back',
    continueBtn: 'Continue',
    cancelBtn: 'Cancel',
    saveBtn: 'Save',
    editBtn: 'Edit',
    downloadPdfBtn: 'Download PDF',
    downloadTxtBtn: 'Download TXT',
    suggestedQ1: 'Can I vote in my cooperative election?',
    suggestedQ2: 'What are my rights as a cooperative society member?',
    suggestedQ3: 'How do I file a grievance against the managing committee?',
    suggestedQ4: 'What documents are required to register a cooperative?',
    voiceListening: 'Listening to your voice...',
    voiceProcessing: 'Understanding your request...',
    voiceSpeaking: 'Responding in your language...',
    voiceIdle: 'Tap microphone to speak',
  },
  te: {
    appName: 'కో-ఆప్ సహాయక్ (Co-opSahayak)',
    appSubtitle: 'సహకార & న్యాయ సహాయ వేదిక (AI Helpdesk)',
    navHome: 'హోమ్',
    navAsk: 'ప్రశ్నించండి',
    navGuided: 'మార్గదర్శక పనులు',
    navRights: 'నా హక్కులు',
    navGrievance: 'ఫిర్యాదు దాఖలు',
    navKnowledge: 'జ్ఞాన భాండాగారం',
    navVoice: 'వాయిస్ సహాయకుడు',
    navProfile: 'నా ప్రొఫైల్',
    navSettings: 'సెట్టింగ్‌లు',
    welcomeHero: 'ఈ రోజు మీ సహకార సంఘం విషయంలో మేము మీకు ఎలా సహాయపడగలం?',
    heroSubtitle: 'నియమావళి, సభ్యుల హక్కులు, ఎన్నికల నిబంధనలు తెలుసుకోండి మరియు అధికారిక ఫిర్యాదు పత్రం రూపొందించండి.',
    askCardTitle: 'ప్రశ్న అడగండి',
    askCardDesc: 'చట్టాలు, ఉపనియమాలు మరియు ఓటింగ్ హక్కులపై స్పష్టమైన సమాధానాలు పొందండి.',
    guidedCardTitle: 'మార్గదర్శక పనులు',
    guidedCardDesc: 'సహకార సంఘ విధానాలను దశలవారీగా సులభంగా పూర్తి చేయండి.',
    grievanceCardTitle: 'ఫిర్యాదు దాఖలు చేయండి',
    grievanceCardDesc: 'నిబంధనల ఆధారంగా అధికారిక ఫిర్యాదు పత్రాన్ని సిద్ధం చేయండి.',
    rightsCardTitle: 'నా హక్కులు',
    rightsCardDesc: 'సహకార సంఘంలో మీ చట్టబద్ధమైన హక్కులు మరియు బాధ్యతలు తెలుసుకోండి.',
    voiceCardTitle: 'వాయిస్ సహాయకుడు',
    voiceCardDesc: 'మీ మాతృభాష తెలుగులోనే సులభంగా మాట్లాడండి.',
    knowledgeCardTitle: 'జ్ఞాన భాండాగారం & మూలాలు',
    knowledgeCardDesc: 'ఈ సమాధానాల వెనుక ఉన్న చట్టాలు మరియు ఉపనియమాలను పరిశీలించండి.',
    activeWorkflowNotice: 'మీ వద్ద ఒక అసంపూర్ణ పని ఉంది',
    resumeTaskBtn: 'పనిని కొనసాగించండి',
    sampleQuestionsLabel: 'తరచుగా అడిగే ప్రశ్నలు:',
    typePlaceholder: 'తెలుగులో అడగండి (ఉదా: నా సహకార సంఘ ఎన్నికలలో నేను ఓటు వేయవచ్చా?)...',
    sendBtn: 'పంపండి',
    voiceBtn: 'మాట్లాడండి',
    clearChatBtn: 'చాట్ తొలగించండి',
    sourcesLabel: 'ధృవీకరించబడిన చట్టపరమైన మూలాలు',
    demoDataBadge: 'డెమో జ్ఞాన భాండాగారం',
    disclaimerText: 'గమనిక: ఈ సహాయకుడు సహకార ఉపనిబంధనల ఆధారంగా మార్గదర్శకత్వం అందిస్తుంది. ఇది న్యాయవాది సలహాకు ప్రత్యామ్నాయం కాదు.',
    closeBtn: 'మూసివేయి',
    backBtn: 'వెనుకకు',
    continueBtn: 'కొనసాగించు',
    cancelBtn: 'రద్దు చేయి',
    saveBtn: 'భద్రపరచు',
    editBtn: 'సవరించు',
    downloadPdfBtn: 'PDF డౌన్‌లోడ్',
    downloadTxtBtn: 'TXT డౌన్‌లోడ్',
    suggestedQ1: 'నా సహకార సంఘ ఎన్నికలలో నేను ఓటు వేయవచ్చా?',
    suggestedQ2: 'సహకార సంఘ సభ్యుడిగా నా హక్కులు ఏమిటి?',
    suggestedQ3: 'మేనేజింగ్ కమిటీపై ఫిర్యాదు ఎలా దాఖలు చేయాలి?',
    suggestedQ4: 'సహకార సంఘం నమోదుకు ఏ పత్రాలు కావాలి?',
    voiceListening: 'మీరు మాట్లాడేది వింటున్నాము...',
    voiceProcessing: 'మీ ప్రశ్నకు సమాధానం సిద్ధం చేస్తున్నాము...',
    voiceSpeaking: 'తెలుగులో సమాధానం చెబుతున్నాము...',
    voiceIdle: 'మాట్లాడటానికి మైక్రోఫోన్ నొక్కండి',
  },
  hi: {
    appName: 'को-ऑप सहायक (Co-opSahayak)',
    appSubtitle: 'सहकारी एवं कानूनी सहायता केंद्र (AI Helpdesk)',
    navHome: 'होम',
    navAsk: 'प्रश्न पूछें',
    navGuided: 'मार्गदर्शित कार्य',
    navRights: 'मेरे अधिकार',
    navGrievance: 'शिकायत दर्ज करें',
    navKnowledge: 'दस्तावेज़ व स्रोत',
    navVoice: 'वॉयस सहायक',
    navProfile: 'मेरी प्रोफाइल',
    navSettings: 'सेटिंग्स',
    welcomeHero: 'आज हम आपकी सहकारी समिति के लिए क्या सहायता कर सकते हैं?',
    heroSubtitle: 'सहकारी नियम, सदस्य अधिकार, चुनाव प्रक्रिया और आधिकारिक शिकायत पत्र तैयार करें।',
    askCardTitle: 'प्रश्न पूछें',
    askCardDesc: 'सहकारी नियमों, उपनियमों और प्रक्रियाओं पर सटीक उत्तर पाएं।',
    guidedCardTitle: 'मार्गदर्शित कार्य',
    guidedCardDesc: 'सहकारी प्रक्रियाओं को चरण-दर-चरण आसानी से समझें और पूरा करें।',
    grievanceCardTitle: 'शिकायत दर्ज करें',
    grievanceCardDesc: 'उपनियमों के अनुसार संरचित शिकायत पत्र तैयार और डाउनलोड करें।',
    rightsCardTitle: 'मेरे अधिकार',
    rightsCardDesc: 'एक सदस्य के रूप में अपने कानूनी अधिकारों और जिम्मेदारियों को जानें।',
    voiceCardTitle: 'वॉयस सहायक',
    voiceCardDesc: 'अपनी पसंदीदा भाषा में सीधे बोलकर सवाल पूछें।',
    knowledgeCardTitle: 'दस्तावेज़ व स्रोत',
    knowledgeCardDesc: 'सहकारी अधिनियमों, उपनियमों व संदर्भ दस्तावेज़ों की जांच करें।',
    activeWorkflowNotice: 'आपका एक अधूरा कार्य प्रगति पर है',
    resumeTaskBtn: 'कार्य जारी रखें',
    sampleQuestionsLabel: 'अक्सर पूछे जाने वाले प्रश्न:',
    typePlaceholder: 'अपनी भाषा में पूछें (उदा: क्या मैं सहकारी चुनाव में वोट दे सकता हूँ?)...',
    sendBtn: 'भेजें',
    voiceBtn: 'बोलें',
    clearChatBtn: 'चैट साफ़ करें',
    sourcesLabel: 'सत्यापित स्रोत एवं संदर्भ',
    demoDataBadge: 'डेमो नॉलेज बेस',
    disclaimerText: 'सूचना: यह सहायक सहकारी उपनियमों पर आधारित जानकारी प्रदान करता है। यह औपचारिक कानूनी परामर्श का विकल्प नहीं है।',
    closeBtn: 'बंद करें',
    backBtn: 'पीछे',
    continueBtn: 'आगे बढ़ें',
    cancelBtn: 'रद्द करें',
    saveBtn: 'सहेजें',
    editBtn: 'संपादित करें',
    downloadPdfBtn: 'PDF डाउनलोड करें',
    downloadTxtBtn: 'TXT डाउनलोड करें',
    suggestedQ1: 'क्या मैं अपनी सहकारी समिति के चुनाव में वोट दे सकता हूँ?',
    suggestedQ2: 'सहकारी समिति सदस्य के रूप में मेरे क्या अधिकार हैं?',
    suggestedQ3: 'प्रबंध समिति के विरुद्ध शिकायत कैसे दर्ज करें?',
    suggestedQ4: 'सहकारी समिति के पंजीकरण के लिए किन दस्तावेज़ों की आवश्यकता है?',
    voiceListening: 'आपकी आवाज़ सुन रहे हैं...',
    voiceProcessing: 'आपकी बात समझ रहे हैं...',
    voiceSpeaking: 'उत्तर बोल रहे हैं...',
    voiceIdle: 'बोलने के लिए माइक दबाएं',
  },
  kn: {
    appName: 'ಕೋ-ಆಪ್ ಸಹಾಯಕ (Co-opSahayak)',
    appSubtitle: 'ಸಹಕಾರಿ ಮತ್ತು ಕಾನೂನು ಸಹಾಯವಾಣಿ',
    navHome: 'ಮುಖಪುಟ',
    navAsk: 'ಪ್ರಶ್ನೆ ಕೇಳಿ',
    navGuided: 'ಮಾರ್ಗದರ್ಶಿ ಕಾರ್ಯಗಳು',
    navRights: 'ನನ್ನ ಹಕ್ಕುಗಳು',
    navGrievance: 'ದೂರು ಸಲ್ಲಿಸಿ',
    navKnowledge: 'ಜ್ಞಾನ ಮತ್ತು ಮೂಲಗಳು',
    navVoice: 'ಧ್ವನಿ ಸಹಾಯಕ',
    navProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    navSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    welcomeHero: 'ಇಂದು ನಿಮ್ಮ ಸಹಕಾರ ಸಂಘಕ್ಕೆ ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    heroSubtitle: 'ಆಡಳಿತ ನಿಯಮಗಳು, ಸದಸ್ಯರ ಹಕ್ಕುಗಳು ಮತ್ತು ದೂರು ಪತ್ರವನ್ನು ಸುಲಭವಾಗಿ ಸಿದ್ಧಪಡಿಸಿ.',
    askCardTitle: 'ಪ್ರಶ್ನೆ ಕೇಳಿ',
    askCardDesc: 'ಕಾನೂನುಗಳು, ಉಪನಿಯಮಗಳು ಮತ್ತು ಹಕ್ಕುಗಳ ಬಗ್ಗೆ ಸ್ಪಷ್ಟ ಉತ್ತರ ಪಡೆಯಿರಿ.',
    guidedCardTitle: 'ಮಾರ್ಗದರ್ಶಿ ಕಾರ್ಯಗಳು',
    guidedCardDesc: 'ಹಂತ-ಹಂತವಾಗಿ ಕಾರ್ಯವಿಧಾನಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
    grievanceCardTitle: 'ದೂರು ಸಲ್ಲಿಸಿ',
    grievanceCardDesc: 'ನಿಯಮಾನುಸಾರ ಅಧಿಕೃತ ದೂರು ಪತ್ರವನ್ನು ರಚಿಸಿ.',
    rightsCardTitle: 'ನನ್ನ ಹಕ್ಕುಗಳು',
    rightsCardDesc: 'ಸದಸ್ಯರಾಗಿ ನಿಮ್ಮ ಶಾಸನಬದ್ಧ ಹಕ್ಕುಗಳನ್ನು ತಿಳಿಯಿರಿ.',
    voiceCardTitle: 'ಧ್ವನಿ ಸಹಾಯಕ',
    voiceCardDesc: 'ನಿಮ್ಮ ಮಾತೃಭಾಷೆ ಕನ್ನಡದಲ್ಲೇ ಮಾತನಾಡಿ.',
    knowledgeCardTitle: 'ಜ್ಞಾನ ಮತ್ತು ಮೂಲಗಳು',
    knowledgeCardDesc: 'ಉಪನಿಯಮಗಳು ಮತ್ತು ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    activeWorkflowNotice: 'ನಿಮ್ಮ ಬಳಿ ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಕೆಲಸವಿದೆ',
    resumeTaskBtn: 'ಮುಂದುವರಿಸಿ',
    sampleQuestionsLabel: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು:',
    typePlaceholder: 'ಕನ್ನಡದಲ್ಲಿ ಕೇಳಿ (ಉದಾ: ಚುನಾವಣೆಯಲ್ಲಿ ಮತ ಚಲಾಯಿಸಬಹುದೇ?)...',
    sendBtn: 'ಕಳುಹಿಸಿ',
    voiceBtn: 'ಮಾತನಾಡಿ',
    clearChatBtn: 'ಚಾಟ್ ಅಳಿಸಿ',
    sourcesLabel: 'ಪರಿಶೀಲಿಸಿದ ಮೂಲಗಳು',
    demoDataBadge: 'ಡೆಮೊ ಮಾಹಿತಿ ಕೋಶ',
    disclaimerText: 'ಸೂಚನೆ: ಇದು ಸಹಕಾರಿ ಉಪನಿಯಮಗಳ ಆಧಾರಿತ ಮಾಹಿತಿ ನೀಡುತ್ತದೆ. ವಕೀಲರ ಪರ್ಯಾಯವಲ್ಲ.',
    closeBtn: 'ಮುಚ್ಚು',
    backBtn: 'ಹಿಂದೆ',
    continueBtn: 'ಮುಂದುವರಿ',
    cancelBtn: 'ರದ್ದುಮಾಡು',
    saveBtn: 'ಉಳಿಸು',
    editBtn: 'ತಿದ್ದು',
    downloadPdfBtn: 'PDF ಡೌನ್‌ಲೋಡ್',
    downloadTxtBtn: 'TXT ಡೌನ್‌ಲೋಡ್',
    suggestedQ1: 'ನನ್ನ ಸಹಕಾರ ಸಂಘದ ಚುನಾವಣೆಯಲ್ಲಿ ನಾನು ಮತ ಚಲಾಯಿಸಬಹುದೇ?',
    suggestedQ2: 'ಸಹಕಾರ ಸಂಘದ ಸದಸ್ಯನಾಗಿ ನನ್ನ ಹಕ್ಕುಗಳೇನು?',
    suggestedQ3: 'ಆಡಳಿತ ಮಂಡಳಿ ವಿರುದ್ಧ ದೂರು ದಾಖಲಿಸುವುದು ಹೇಗೆ?',
    suggestedQ4: 'ಸಹಕಾರ ಸಂಘ ನೋಂದಣಿಗೆ ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?',
    voiceListening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ...',
    voiceProcessing: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    voiceSpeaking: 'ಉತ್ತರಿಸಲಾಗುತ್ತಿದೆ...',
    voiceIdle: 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
  },
  ta: {
    appName: 'கோ-ஆப் சகாயக் (Co-opSahayak)',
    appSubtitle: 'கூட்டுறவு மற்றும் சட்ட உதவி மையம்',
    navHome: 'முகப்பு',
    navAsk: 'கேள்வி கேட்க',
    navGuided: 'வழிகாட்டப்பட்ட பணிகள்',
    navRights: 'என் உரிமைகள்',
    navGrievance: 'புகார் பதிவு செய்ய',
    navKnowledge: 'ஆதாரங்கள் & விதிகள்',
    navVoice: 'குரல் உதவியாளர்',
    navProfile: 'என் விவரக்குறிப்பு',
    navSettings: 'அமைப்புகள்',
    welcomeHero: 'உங்கள் கூட்டுறவு சங்கத்திற்கு இன்று நாங்கள் எவ்வாறு உதவலாம்?',
    heroSubtitle: 'விதிகள், உறுப்பினர் உரிமைகள், தேர்தல் நடைமுறைகளை அறிந்து மனுக்களைத் தயாரிக்கவும்.',
    askCardTitle: 'கேள்வி கேட்கவும்',
    askCardDesc: 'சட்டங்கள் மற்றும் விதிகள் பற்றிய தெளிவான பதில்களைப் பெறுங்கள்.',
    guidedCardTitle: 'வழிகாட்டப்பட்ட பணிகள்',
    guidedCardDesc: 'பொதுவான நடைமுறைகளை படி படியாக முடிக்கவும்.',
    grievanceCardTitle: 'புகார் மனு தயார் செய்ய',
    grievanceCardDesc: 'அதிகாரப்பூர்வ புகார் கடிதத்தை எளிதாக உருவாக்கவும்.',
    rightsCardTitle: 'என் உரிமைகள்',
    rightsCardDesc: 'உறுப்பினர் உரிமைகள் மற்றும் பொறுப்புகளைப் புரிந்து கொள்ளுங்கள்.',
    voiceCardTitle: 'குரல் உதவியாளர்',
    voiceCardDesc: 'தமிழிலேயே பேசி விரைவாகப் பதில் பெறுங்கள்.',
    knowledgeCardTitle: 'ஆதாரங்கள் & விதிகள்',
    knowledgeCardDesc: 'கூட்டுறவு துணை விதிகள் மற்றும் சட்ட ஆவணங்களை ஆராயுங்கள்.',
    activeWorkflowNotice: 'முடிக்கப்படாத பணி நிலுவையில் உள்ளது',
    resumeTaskBtn: 'தொடரவும்',
    sampleQuestionsLabel: 'அடிக்கடி கேட்கப்படும் கேள்விகள்:',
    typePlaceholder: 'தமிழில் கேளுங்கள் (எ.கா: நான் தேர்தலில் வாக்களிக்க முடியுமா?)...',
    sendBtn: 'அனுப்புக',
    voiceBtn: 'பேசுக',
    clearChatBtn: 'அழிக்க',
    sourcesLabel: 'சரிபார்க்கப்பட்ட ஆதாரங்கள்',
    demoDataBadge: 'மாதிரி அறிவுத் தளம்',
    disclaimerText: 'குறிப்பு: இது கூட்டுறவு விதிகளின் அடிப்படையிலான வழிகாட்டலாகும். சட்ட ஆலோசகரின் மாற்றல்ல.',
    closeBtn: 'மூடு',
    backBtn: 'பின்செல்',
    continueBtn: 'தொடர்க',
    cancelBtn: 'ரத்து',
    saveBtn: 'சேமி',
    editBtn: 'திருத்து',
    downloadPdfBtn: 'PDF பதிவிறக்கம்',
    downloadTxtBtn: 'TXT பதிவிறக்கம்',
    suggestedQ1: 'கூட்டுறவு சங்கத் தேர்தலில் நான் வாக்களிக்க முடியுமா?',
    suggestedQ2: 'கூட்டுறவு சங்க உறுப்பினராக எனது உரிமைகள் என்ன?',
    suggestedQ3: 'நிர்வாகக் குழுவிற்கு எதிராகப் புகார் அளிப்பது எப்படி?',
    suggestedQ4: 'கூட்டுறவு சங்கம் பதிவு செய்ய என்ன ஆவணங்கள் தேவை?',
    voiceListening: 'கேட்கிறது...',
    voiceProcessing: 'புரிந்து கொள்கிறது...',
    voiceSpeaking: 'பதிலளிக்கிறது...',
    voiceIdle: 'பேச மைக் அழுத்தவும்',
  },
  // Comprehensive native translations for all supported languages
  mr: {
    appName: 'को-ऑप सहाय्यक (Co-opSahayak)',
    appSubtitle: 'सहकारी व कायदेशीर मदत केंद्र (AI Helpdesk)',
    navHome: 'मुख्यपृष्ठ',
    navAsk: 'प्रश्न विचारा',
    navGuided: 'मार्गदर्शित कार्ये',
    navRights: 'माझे हक्क',
    navGrievance: 'तक्रार नोंदवा',
    navKnowledge: 'दस्तऐवज व स्रोत',
    navVoice: 'आवाज सहाय्यक',
    navProfile: 'माझे प्रोफाइल',
    navSettings: 'सेटिंग्ज',
    welcomeHero: 'आज आम्ही आपल्या सहकारी संस्थेसाठी काय मदत करू शकतो?',
    heroSubtitle: 'सहकारी उपनियम, सदस्य हक्क, निवडणूक नियम आणि अधिकृत तक्रार अर्ज तयार करा.',
    askCardTitle: 'प्रश्न विचारा',
    askCardDesc: 'सहकारी कायदे, उपनियम आणि मतदानाच्या नियमांवर अचूक उत्तरे मिळवा.',
    guidedCardTitle: 'मार्गदर्शित कार्ये',
    guidedCardDesc: 'सहकारी प्रक्रिया टप्प्याटप्प्याने सहजपणे पूर्ण करा.',
    grievanceCardTitle: 'तक्रार नोंदवा',
    grievanceCardDesc: 'उपनियमांनुसार अधिकृत तक्रार पत्र तयार आणि डाउनलोड करा.',
    rightsCardTitle: 'माझे हक्क',
    rightsCardDesc: 'सदस्य म्हणून आपले कायदेशीर अधिकार आणि जबाबदाऱ्या जाणून घ्या.',
    voiceCardTitle: 'आवाज सहाय्यक',
    voiceCardDesc: 'आपल्या मराठी भाषेत थेट बोलून प्रश्न विचारा.',
    knowledgeCardTitle: 'दस्तऐवज व स्रोत',
    knowledgeCardDesc: 'सहकारी संस्था अधिनियम आणि उपनियमांची तपासणी करा.',
    activeWorkflowNotice: 'आपले एक अपूर्ण कार्य चालू आहे',
    resumeTaskBtn: 'कार्य चालू ठेवा',
    sampleQuestionsLabel: 'नेहमी विचारले जाणारे प्रश्न:',
    typePlaceholder: 'मराठीत विचारा (उदा: मी सहकारी निवडणुकीत मतदान करू शकतो का?)...',
    sendBtn: 'पाठवा',
    voiceBtn: 'बोला',
    clearChatBtn: 'चॅट साफ करा',
    sourcesLabel: 'प्रमाणित कायदेशीर स्रोत',
    demoDataBadge: 'डेमो माहिती केंद्र',
    disclaimerText: 'सूचना: हा सहाय्यक सहकारी उपनियमांवर आधारित माहिती देतो. हा कायदेशीर सल्लागाराचा पर्याय नाही.',
    closeBtn: 'बंद करा',
    backBtn: 'मागे',
    continueBtn: 'पुढे जा',
    cancelBtn: 'रद्द करा',
    saveBtn: 'जतन करा',
    editBtn: 'संपादित करा',
    downloadPdfBtn: 'PDF डाउनलोड करा',
    downloadTxtBtn: 'TXT डाउनलोड करा',
    suggestedQ1: 'मी माझ्या सहकारी संस्थेच्या निवडणुकीत मतदान करू शकतो का?',
    suggestedQ2: 'सहकारी संस्थेचा सदस्य म्हणून माझे अधिकार काय आहेत?',
    suggestedQ3: 'व्यवस्थापकीय समितीविरुद्ध तक्रार कशी नोंदवावी?',
    suggestedQ4: 'सहकारी संस्था नोंदणीसाठी कोणती कागदपत्रे लागतात?',
    voiceListening: 'आपला आवाज ऐकत आहे...',
    voiceProcessing: 'आपला प्रश्न समजून घेत आहे...',
    voiceSpeaking: 'मराठीत उत्तर देत आहे...',
    voiceIdle: 'बोलण्यासाठी माइक दाबा',
  },
  bn: {
    appName: 'কো-অপ সহায়ক (Co-opSahayak)',
    appSubtitle: 'সমবায় ও আইনি সহায়তা কেন্দ্র',
    navHome: 'হোম',
    navAsk: 'প্রশ্ন জিজ্ঞাসা করুন',
    navGuided: 'নির্দেশিত কাজ',
    navRights: 'আমার অধিকার',
    navGrievance: 'অভিযোগ দায়ের করুন',
    navKnowledge: 'নথি ও উৎস',
    navVoice: 'ভয়েস সহকারী',
    navProfile: 'আমার প্রোফাইল',
    navSettings: 'সেটিংস',
    welcomeHero: 'আজ আপনার সমবায় সমিতির জন্য আমরা কীভাবে সাহায্য করতে পারি?',
    heroSubtitle: 'সমবায় উপ-আইন, সদস্য অধিকার, নির্বাচন পদ্ধতি জানুন এবং অভিযোগ পত্র প্রস্তুত করুন।',
    askCardTitle: 'প্রশ্ন জিজ্ঞাসা করুন',
    askCardDesc: 'সমবায় আইন ও অধিকার সম্পর্কে স্পষ্ট উত্তর পান।',
    guidedCardTitle: 'নির্দেশিত কাজ',
    guidedCardDesc: 'ধাপে ধাপে সমবায় পদ্ধতিগুলো সম্পন্ন করুন।',
    grievanceCardTitle: 'অভিযোগ দায়ের করুন',
    grievanceCardDesc: 'নিয়ম অনুযায়ী আনুষ্ঠানিক অভিযোগ পত্র প্রস্তুত করুন।',
    rightsCardTitle: 'আমার অধিকার',
    rightsCardDesc: 'সদস্য হিসেবে আপনার বিধিবদ্ধ অধিকার ও দায়িত্ব জানুন।',
    voiceCardTitle: 'ভয়েস সহকারী',
    voiceCardDesc: 'আপনার পছন্দের বাংলা ভাষায় কথা বলুন।',
    knowledgeCardTitle: 'নথি ও উৎস',
    knowledgeCardDesc: 'সমবায় আইন ও উপ-আইন পর্যালোচনা করুন।',
    activeWorkflowNotice: 'আপনার একটি অসমাপ্ত কাজ চলমান আছে',
    resumeTaskBtn: 'কাজ চালিয়ে যান',
    sampleQuestionsLabel: 'সাধারণ প্রশ্নাবলী:',
    typePlaceholder: 'বাংলায় জিজ্ঞাসা করুন (যেমন: আমি কি নির্বাচনে ভোট দিতে পারি?)...',
    sendBtn: 'পাঠান',
    voiceBtn: 'বলুন',
    clearChatBtn: 'চ্যাট মুছুন',
    sourcesLabel: 'যাচাইকৃত আইনি উৎস',
    demoDataBadge: 'ডেমো জ্ঞান ভাণ্ডার',
    disclaimerText: 'বিজ্ঞপ্তি: এই সহকারী সমবায় উপ-আইনের ভিত্তিতে তথ্য প্রদান করে। এটি আইনি পরামর্শের বিকল্প নয়।',
    closeBtn: 'বন্ধ করুন',
    backBtn: 'ফিরে যান',
    continueBtn: 'এগিয়ে যান',
    cancelBtn: 'বাতিল করুন',
    saveBtn: 'সংরক্ষণ করুন',
    editBtn: 'সম্পাদনা করুন',
    downloadPdfBtn: 'PDF ডাউনলোড',
    downloadTxtBtn: 'TXT ডাউনলোড',
    suggestedQ1: 'আমি কি আমার সমবায় নির্বাচনে ভোট দিতে পারি?',
    suggestedQ2: 'সমবায় সদস্য হিসেবে আমার অধিকারগুলো কি কি?',
    suggestedQ3: 'ব্যবস্থাপনা কমিটির বিরুদ্ধে কিভাবে অভিযোগ করবেন?',
    suggestedQ4: 'সমবায় সমিতি নিবন্ধনের জন্য কি কি নথি প্রয়োজন?',
    voiceListening: 'আপনার কথা শুনছি...',
    voiceProcessing: 'উত্তর তৈরি হচ্ছে...',
    voiceSpeaking: 'উত্তর বলছি...',
    voiceIdle: 'বলতে মাইক চাপুন',
  },
  gu: {
    appName: 'કો-ઓપ સહાયક (Co-opSahayak)',
    appSubtitle: 'સહકારી અને કાનૂની સહાયતા કેન્દ્ર',
    navHome: 'હોમ',
    navAsk: 'પ્રશ્ન પૂછો',
    navGuided: 'માર્ગદર્શિત કાર્યો',
    navRights: 'મારા અધિકારો',
    navGrievance: 'ફરિયાદ નોંધાવો',
    navKnowledge: 'દસ્તાવેજો અને સ્ત્રોતો',
    navVoice: 'વોઇસ સહાયક',
    navProfile: 'મારી પ્રોફાઇલ',
    navSettings: 'સેટિંગ્સ',
    welcomeHero: 'આજે તમારી સહકારી મંડળી માટે અમે કેવી રીતે મદદ કરી શકીએ?',
    heroSubtitle: 'સહકારી ઉપનિયમો, સભ્ય અધિકારો, ચૂંટણીના નિયમો જાણો અને ફરિયાદ પત્ર તૈયાર કરો.',
    askCardTitle: 'પ્રશ્ન પૂછો',
    askCardDesc: 'સહકારી કાયદા અને અધિકારો અંગે સ્પષ્ટ જવાબો મેળવો.',
    guidedCardTitle: 'માર્ગદર્શિત કાર્યો',
    guidedCardDesc: 'પગલાવાર સહકારી પ્રક્રિયાઓ પૂર્ણ કરો.',
    grievanceCardTitle: 'ફરિયાદ નોંધાવો',
    grievanceCardDesc: 'નિયમો અનુસાર સત્તાવાર ફરિયાદ પત્ર તૈયાર કરો.',
    rightsCardTitle: 'મારા અધિકારો',
    rightsCardDesc: 'સભ્ય તરીકે તમારા કાનૂની અધિકારો સમજો.',
    voiceCardTitle: 'વોઇસ સહાયક',
    voiceCardDesc: 'તમારી માતૃભાષા ગુજરાતીમાં બોલીને પૂછો.',
    knowledgeCardTitle: 'દસ્તાવેજો અને સ્ત્રોતો',
    knowledgeCardDesc: 'સહકારી કાયદા અને ઉપનિયમો ચકાસો.',
    activeWorkflowNotice: 'તમારું અધૂરું કાર્ય ચાલુ છે',
    resumeTaskBtn: 'કાર્ય ચાલુ રાખો',
    sampleQuestionsLabel: 'વારંવાર પૂછાતા પ્રશ્નો:',
    typePlaceholder: 'ગુજરાતીમાં પૂછો (દા.ત: શું હું ચૂંટણીમાં મત આપી શકું?)...',
    sendBtn: 'મોકલો',
    voiceBtn: 'બોલો',
    clearChatBtn: 'ચેટ સાફ કરો',
    sourcesLabel: 'પ્રમાણિત કાનૂની સ્ત્રોતો',
    demoDataBadge: 'ડેમો જ્ઞાન ભંડાર',
    disclaimerText: 'નોંધ: આ સહાયક સહકારી ઉપનિયમો આધારિત માહિતી પૂરી પાડે છે. તે કાનૂની સલાહનો વિકલ્પ નથી.',
    closeBtn: 'બંધ કરો',
    backBtn: 'પાછળ',
    continueBtn: 'આગળ વધો',
    cancelBtn: 'રદ કરો',
    saveBtn: 'સાચવો',
    editBtn: 'સુધારો',
    downloadPdfBtn: 'PDF ડાઉનલોડ',
    downloadTxtBtn: 'TXT ડાઉનલોડ',
    suggestedQ1: 'શું હું મારી સહકારી મંડળીની ચૂંટણીમાં મત આપી શકું?',
    suggestedQ2: 'સહકારી મંડળીના સભ્ય તરીકે મારા અધિકારો શું છે?',
    suggestedQ3: 'મેનેજિંગ કમિટી સામે ફરિયાદ કેવી રીતે કરવી?',
    suggestedQ4: 'સહકારી મંડળીની નોંધણી માટે કયા દસ્તાવેજો જરૂરી છે?',
    voiceListening: 'તમારો અવાજ સાંભળી રહ્યા છીએ...',
    voiceProcessing: 'સમજી રહ્યા છીએ...',
    voiceSpeaking: 'ગુજરાતીમાં જવાબ આપી રહ્યા છીએ...',
    voiceIdle: 'બોલવા માટે માઇક દબાવો',
  },
  ml: {
    appName: 'കോ-ഓപ് സഹായക് (Co-opSahayak)',
    appSubtitle: 'സഹകരണ & നിയമ സഹായ കേന്ദ്രം',
    navHome: 'ഹോം',
    navAsk: 'ചോദ്യം ചോദിക്കുക',
    navGuided: 'മാർഗ്ഗനിർദ്ദേശ ജോലികൾ',
    navRights: 'എന്റെ അവകാശങ്ങൾ',
    navGrievance: 'പരാതി നൽകുക',
    navKnowledge: 'രേഖകളും ഉറവിടങ്ങളും',
    navVoice: 'ശബ്ദ സഹായി',
    navProfile: 'പ്രൊഫൈൽ',
    navSettings: 'ക്രമീകരണങ്ങൾ',
    welcomeHero: 'ഇന്ന് നിങ്ങളുടെ സഹകരണ സംഘത്തിനായി ഞങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാനാകും?',
    heroSubtitle: 'നിയമങ്ങൾ, അംഗങ്ങളുടെ അവകാശങ്ങൾ, തിരഞ്ഞെടുപ്പ് വിവരങ്ങൾ അറിയുക, പരാതി കത്ത് തയ്യാറാക്കുക.',
    askCardTitle: 'ചോദ്യം ചോദിക്കുക',
    askCardDesc: 'സഹകരണ നിയമങ്ങളിലും അവകാശങ്ങളിലും വ്യക്തമായ ഉത്തരങ്ങൾ നേടുക.',
    guidedCardTitle: 'മാർഗ്ഗനിർദ്ദേശ ജോലികൾ',
    guidedCardDesc: 'ഘട്ടം ഘട്ടമായി സഹകരണ പ്രക്രിയകൾ പൂർത്തിയാക്കുക.',
    grievanceCardTitle: 'പരാതി നൽകുക',
    grievanceCardDesc: 'ഔദ്യോഗിക പരാതി കത്ത് തയ്യാറാക്കുക.',
    rightsCardTitle: 'എന്റെ അവകാശങ്ങൾ',
    rightsCardDesc: 'നിയമപരമായ അംഗത്വ അവകാശങ്ങൾ മനസ്സിലാക്കുക.',
    voiceCardTitle: 'ശബ്ദ സഹായി',
    voiceCardDesc: 'മലയാളത്തിൽ സംസാരിച്ച് ഉത്തരം നേടുക.',
    knowledgeCardTitle: 'രേഖകളും ഉറവിടങ്ങളും',
    knowledgeCardDesc: 'സഹകരണ നിയമങ്ങളും ഉപനിയമങ്ങളും പരിശോധിക്കുക.',
    activeWorkflowNotice: 'നിങ്ങൾക്ക് പൂർത്തിയാകാത്ത ഒരു ജോലിയുണ്ട്',
    resumeTaskBtn: 'തുടരുക',
    sampleQuestionsLabel: 'സാധാരണ ചോദ്യങ്ങൾ:',
    typePlaceholder: 'മലയാളത്തിൽ ചോദിക്കുക (ഉദാ: എനിക്ക് തിരഞ്ഞെടുപ്പിൽ വോട്ട് ചെയ്യാമോ?)...',
    sendBtn: 'അയക്കുക',
    voiceBtn: 'സംസാരിക്കുക',
    clearChatBtn: 'ചാറ്റ് മായ്ക്കുക',
    sourcesLabel: 'സാക്ഷ്യപ്പെടുത്തിയ ഉറവിടങ്ങൾ',
    demoDataBadge: 'ഡെമോ വിജ്ഞാന കോശം',
    disclaimerText: 'ശ്രദ്ധിക്കുക: സഹകരണ ഉപനിയമങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ള വിവരങ്ങളാണിത്. നിയമോപദേശത്തിന് പകരമല്ല.',
    closeBtn: 'അടയ്ക്കുക',
    backBtn: 'പിന്നോട്ട്',
    continueBtn: 'തുടരുക',
    cancelBtn: 'റദ്ദാക്കുക',
    saveBtn: 'സൂക്ഷിക്കുക',
    editBtn: 'തിരുത്തുക',
    downloadPdfBtn: 'PDF ഡൗൺലോഡ്',
    downloadTxtBtn: 'TXT ഡൗൺലോഡ്',
    suggestedQ1: 'സഹകരണ സംഘം തിരഞ്ഞെടുപ്പിൽ എനിക്ക് വോട്ട് ചെയ്യാമോ?',
    suggestedQ2: 'ഒരു അംഗമെന്ന നിലയിൽ എന്റെ അവകാശങ്ങൾ എന്തൊക്കെയാണ്?',
    suggestedQ3: 'മാനേജിംഗ് കമ്മിറ്റിക്കെതിരെ പരാതി നൽകുന്നത് എങ്ങനെ?',
    suggestedQ4: 'സൊസൈറ്റി രജിസ്ട്രേഷന് എന്തൊക്കെ രേഖകൾ വേണം?',
    voiceListening: 'കേൾക്കുന്നു...',
    voiceProcessing: 'ഉത്തരം തയ്യാറാക്കുന്നു...',
    voiceSpeaking: 'മലയാളത്തിൽ മറുപടി പറയുന്നു...',
    voiceIdle: 'സംസാരിക്കാൻ മൈക്ക് അമർത്തുക',
  },
  pa: {
    appName: 'ਕੋ-ਆਪ ਸਹਾਇਕ (Co-opSahayak)',
    appSubtitle: 'ਸਹਿਕਾਰੀ ਅਤੇ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਕੇਂਦਰ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navAsk: 'ਸਵਾਲ ਪੁੱਛੋ',
    navGuided: 'ਸੇਧਿਤ ਕਾਰਜ',
    navRights: 'ਮੇਰੇ ਅਧਿਕਾਰ',
    navGrievance: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    navKnowledge: 'ਦਸਤਾਵੇਜ਼ ਤੇ ਸਰੋਤ',
    navVoice: 'ਅਵਾਜ਼ ਸਹਾਇਕ',
    navProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    navSettings: 'ਸੈਟਿੰਗਾਂ',
    welcomeHero: 'ਅੱਜ ਅਸੀਂ ਤੁਹਾਡੀ ਸਹਿਕਾਰੀ ਸਭਾ ਲਈ ਕੀ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
    heroSubtitle: 'ਨਿਯਮ, ਮੈਂਬਰ ਅਧਿਕਾਰ, ਚੋਣ ਪ੍ਰਕਿਰਿਆ ਸਮਝੋ ਅਤੇ ਸਰਕਾਰੀ ਸ਼ਿਕਾਇਤ ਪੱਤਰ ਤਿਆਰ ਕਰੋ।',
    askCardTitle: 'ਸਵਾਲ ਪੁੱਛੋ',
    askCardDesc: 'ਸਹਿਕਾਰੀ ਕਾਨੂੰਨਾਂ ਅਤੇ ਅਧਿਕਾਰਾਂ ਬਾਰੇ ਸਪੱਸ਼ਟ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ।',
    guidedCardTitle: 'ਸੇਧਿਤ ਕਾਰਜ',
    guidedCardDesc: 'ਕਦਮ-ਦਰ-ਕਦਮ ਪ੍ਰਕਿਰਿਆਵਾਂ ਪੂਰੀਆਂ ਕਰੋ।',
    grievanceCardTitle: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    grievanceCardDesc: 'ਉਪ-ਨਿਯਮਾਂ ਅਨੁਸਾਰ ਰਸਮੀ ਸ਼ਿਕਾਇਤ ਪੱਤਰ ਬਣਾਓ।',
    rightsCardTitle: 'ਮੇਰੇ ਅਧਿਕਾਰ',
    rightsCardDesc: 'ਮੈਂਬਰ ਵਜੋਂ ਆਪਣੇ ਕਾਨੂੰਨੀ ਅਧਿਕਾਰ ਜਾਣੋ।',
    voiceCardTitle: 'ਅਵਾਜ਼ ਸਹਾਇਕ',
    voiceCardDesc: 'ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲ ਕੇ ਸਵਾਲ ਪੁੱਛੋ।',
    knowledgeCardTitle: 'ਦਸਤਾਵੇਜ਼ ਤੇ ਸਰੋਤ',
    knowledgeCardDesc: 'ਸਹਿਕਾਰੀ ਕਾਨੂੰਨਾਂ ਤੇ ਨਿਯਮਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।',
    activeWorkflowNotice: 'ਤੁਹਾਡਾ ਇੱਕ ਅਧੂਰਾ ਕੰਮ ਚੱਲ ਰਿਹਾ ਹੈ',
    resumeTaskBtn: 'ਜਾਰੀ ਰੱਖੋ',
    sampleQuestionsLabel: 'ਆਮ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ:',
    typePlaceholder: 'ਪੰਜਾਬੀ ਵਿੱਚ ਪੁੱਛੋ (ਜਿਵੇਂ: ਕੀ ਮੈਂ ਚੋਣਾਂ ਵਿੱਚ ਵੋਟ ਪਾ ਸਕਦਾ ਹਾਂ?)...',
    sendBtn: 'ਭੇਜੋ',
    voiceBtn: 'ਬੋਲੋ',
    clearChatBtn: 'ਚੈਟ ਸਾਫ਼ ਕਰੋ',
    sourcesLabel: 'ਪ੍ਰਮਾਣਿਤ ਕਾਨੂੰਨੀ ਸਰੋਤ',
    demoDataBadge: 'ਡੈਮੋ ਜਾਣਕਾਰੀ ਭੰਡਾਰ',
    disclaimerText: 'ਸੂਚਨਾ: ਇਹ ਸਹਾਇਕ ਸਹਿਕਾਰੀ ਉਪ-ਨਿਯਮਾਂ ਆਧਾਰਿਤ ਜਾਣਕਾਰੀ ਦਿੰਦਾ ਹੈ। ਇਹ ਕਾਨੂੰਨੀ ਸਲਾਹਕਾਰ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।',
    closeBtn: 'ਬੰਦ ਕਰੋ',
    backBtn: 'ਪਿੱਛੇ',
    continueBtn: 'ਅੱਗੇ ਵਧੋ',
    cancelBtn: 'ਰੱਦ ਕਰੋ',
    saveBtn: 'ਸੰਭਾਲੋ',
    editBtn: 'ਸੋਧੋ',
    downloadPdfBtn: 'PDF ਡਾਊਨਲੋਡ',
    downloadTxtBtn: 'TXT ਡਾਊਨਲੋਡ',
    suggestedQ1: 'ਕੀ ਮੈਂ ਆਪਣੀ ਸਹਿਕਾਰੀ ਸਭਾ ਦੀਆਂ ਚੋਣਾਂ ਵਿੱਚ ਵੋਟ ਪਾ ਸਕਦਾ ਹਾਂ?',
    suggestedQ2: 'ਸਹਿਕਾਰੀ ਮੈਂਬਰ ਵਜੋਂ ਮੇਰੇ ਕੀ ਅਧਿਕਾਰ ਹਨ?',
    suggestedQ3: 'ਪ੍ਰਬੰਧਕੀ ਕਮੇਟੀ ਵਿਰੁੱਧ ਸ਼ਿਕਾਇਤ ਕਿਵੇਂ ਦਰਜ ਕਰੀਏ?',
    suggestedQ4: 'ਸਹਿਕਾਰੀ ਸਭਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਲਈ ਕਿਹੜੇ ਦਸਤਾਵੇਜ਼ ਚਾਹੀਦੇ ਹਨ?',
    voiceListening: 'ਤੁਹਾਡੀ ਅਵਾਜ਼ ਸੁਣ ਰਹੇ ਹਾਂ...',
    voiceProcessing: 'ਜਵਾਬ ਤਿਆਰ ਕਰ ਰਹੇ ਹਾਂ...',
    voiceSpeaking: 'ਪੰਜਾਬੀ ਵਿੱਚ ਜਵਾਬ ਦੇ ਰਹੇ ਹਾਂ...',
    voiceIdle: 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
  },
  or: {
    appName: 'କୋ-ଅପ୍ ସହାୟକ (Co-opSahayak)',
    appSubtitle: 'ସମବାୟ ଓ ଆଇନଗତ ସହାୟତା କେନ୍ଦ୍ର',
    navHome: 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    navAsk: 'ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ',
    navGuided: 'ନିର୍ଦ୍ଦେଶିତ କାର୍ଯ୍ୟ',
    navRights: 'ମୋର ଅଧିକାର',
    navGrievance: 'ଅଭିଯୋਗ ଦାଖଲ କରନ୍ତୁ',
    navKnowledge: 'ଦଲିଲ ଓ ଉତ୍ସ',
    navVoice: 'ଭଏସ୍ ସହାୟକ',
    navProfile: 'ମୋ ପ୍ରୋଫାଇଲ୍',
    navSettings: 'ସେଟିଙ୍ଗ୍ସ',
    welcomeHero: 'ଆଜି ଆପଣଙ୍କ ସମବାୟ ସମିତି ପାଇଁ ଆମେ କିପରି ସାହାଯ୍ୟ କରିପାରିବା?',
    heroSubtitle: 'ସମବାୟ ଉପ-ନିୟମ, ସଦସ୍ୟ ଅଧିକାର, ନିର୍ବାଚନ ପ୍ରକ୍ରିୟା ଜାଣନ୍ତୁ ଓ ଅଭିଯୋଗ ପତ୍ର ପ୍ରସ୍ତୁତ କରନ୍ତୁ।',
    askCardTitle: 'ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ',
    askCardDesc: 'ନିୟମ ଓ ଅଧିକାର ଉପରେ ସ୍ପଷ୍ଟ ଉତ୍ତର ପାଆନ୍ତୁ।',
    guidedCardTitle: 'ନିର୍ଦ୍ଦେଶିତ କାର୍ଯ୍ୟ',
    guidedCardDesc: 'ପଦକ୍ଷେପ ଅନୁଯାୟୀ ପ୍ରକ୍ରିୟା ସମାପ୍ତ କରନ୍ତୁ।',
    grievanceCardTitle: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    grievanceCardDesc: 'ଆନୁଷ୍ଠାନିକ ଅଭିଯୋଗ ପତ୍ର ପ୍ରସ୍ତୁତ କରନ୍ତୁ।',
    rightsCardTitle: 'ମୋର ଅଧିକାର',
    rightsCardDesc: 'ସଦସ୍ୟ ଭାବରେ ଆପଣଙ୍କ ଆଇନଗତ ଅଧିକାର ବୁଝନ୍ତୁ।',
    voiceCardTitle: 'ଭଏସ୍ ସହାୟକ',
    voiceCardDesc: 'ଓଡ଼ିଆରେ କଥା ହୋଇ ସୂଚନା ପାଆନ୍ତୁ।',
    knowledgeCardTitle: 'ଦଲିଲ ଓ ଉତ୍ସ',
    knowledgeCardDesc: 'ସମବାୟ ଉପ-ନିୟମ ଓ ଆଇନଗୁଡ଼ିକ ଯାଞ୍ଚ କରନ୍ତୁ।',
    activeWorkflowNotice: 'ଆପଣଙ୍କର ଏକ ଅସମ୍ପୂର୍ଣ୍ଣ କାର୍ଯ୍ୟ ଚାଲୁଅଛି',
    resumeTaskBtn: 'କାର୍ଯ୍ୟ ଜାରି ରଖନ୍ତୁ',
    sampleQuestionsLabel: 'ସାଧାରଣ ପ୍ରଶ୍ନଗୁଡ଼ିକ:',
    typePlaceholder: 'ଓଡ଼ିଆରେ ପଚାରନ୍ତୁ (ଉଦା: ମୁଁ କଣ ନିର୍ବାଚନରେ ଭୋଟ୍ ଦେଇପାରିବି?)...',
    sendBtn: 'ପଠାନ୍ତୁ',
    voiceBtn: 'କୁହନ୍ତୁ',
    clearChatBtn: 'ଚାଟ୍ ପରିଷ୍କାର କରନ୍ତୁ',
    sourcesLabel: 'ପ୍ରମାଣିତ ଆଇନଗତ ଉତ୍ସ',
    demoDataBadge: 'ଡେମୋ ସୂଚନା ଭଣ୍ଡାର',
    disclaimerText: 'ସୂଚନା: ଏହି ସହାୟକ ସମବାୟ ଉପ-ନିୟମ ଉପରେ ଆଧାରିତ। ଏହା ଆଇନଜୀବୀଙ୍କ ବିକଳ୍ପ ନୁହେଁ।',
    closeBtn: 'ବନ୍ଦ କରନ୍ତୁ',
    backBtn: 'ପଛକୁ',
    continueBtn: 'ଆଗକୁ ବଢ଼ନ୍ତୁ',
    cancelBtn: 'ବାତିଲ୍ କରନ୍ତୁ',
    saveBtn: 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    editBtn: 'ସମ୍ପାଦନ କରନ୍ତୁ',
    downloadPdfBtn: 'PDF ଡାଉନଲୋଡ୍',
    downloadTxtBtn: 'TXT ଡାଉନଲୋଡ୍',
    suggestedQ1: 'ମୁଁ କଣ ମୋ ସମବାୟ ସମିତି ନିର୍ବାଚନରେ ଭୋଟ୍ ଦେଇପାରିବି?',
    suggestedQ2: 'ଜଣେ ସଦସ୍ୟ ଭାବରେ ମୋର ଅଧିକାର କଣ?',
    suggestedQ3: 'ପରିଚାଳନା କମିଟି ବିରୁଦ୍ଧରେ କିପରି ଅଭିଯୋਗ କରିବେ?',
    suggestedQ4: 'ସମବାୟ ସମିତି ପଞ୍ଜୀକରଣ ପାଇଁ କେଉଁ କାଗଜପତ୍ର ଦରକାର?',
    voiceListening: 'ଆପଣଙ୍କ ସ୍ୱର ଶୁଣୁଛୁ...',
    voiceProcessing: 'ବୁଝୁଛୁ...',
    voiceSpeaking: 'ଓଡ଼ିଆରେ ଉତ୍ତର ଦେଉଛୁ...',
    voiceIdle: 'କହିବା ପାଇଁ ମାଇକ୍ ଦବାନ୍ତୁ',
  },
  as: {
    appName: 'কো-অ\'প সহায়ক (Co-opSahayak)',
    appSubtitle: 'সমবায় আৰু আইনী সাহায্য কেন্দ্ৰ',
    navHome: 'মুখ্য পৃষ্ঠা',
    navAsk: 'প্ৰশ্ন সোধক',
    navGuided: 'নিৰ্দেশিত কাৰ্য্য',
    navRights: 'মোৰ অধিকাৰ',
    navGrievance: 'অভিযোগ দাখিল কৰক',
    navKnowledge: 'নথি আৰু উৎস',
    navVoice: 'ভইচ সহায়ক',
    navProfile: 'মোৰ প্ৰ\'ফাইল',
    navSettings: 'ছেটিংছ',
    welcomeHero: 'আজি আপোনাৰ সমবায় সমিতিৰ বাবে আমি কেনেকৈ সহায় কৰিব পাৰোঁ?',
    heroSubtitle: 'সমবায় উপ-নিয়ম, সদস্যৰ অধিকাৰ, নিৰ্বাচনৰ নিয়ম জানক আৰু অভিযোগ পত্ৰ প্ৰস্তুত কৰক।',
    askCardTitle: 'প্ৰশ্ন সোধক',
    askCardDesc: 'সমবায় আইন আৰু অধিকাৰৰ ওপৰত স্পষ্ট উত্তৰ লাভ কৰক।',
    guidedCardTitle: 'নিৰ্দেশিত কাৰ্য্য',
    guidedCardDesc: 'ধাপে ধাপে সমবায় প্ৰক্ৰিয়াসমূহ সম্পূৰ্ণ কৰক।',
    grievanceCardTitle: 'অভিযোগ দাখিল কৰক',
    grievanceCardDesc: 'আইনী নিয়ম অনুসৰি আনুষ্ঠানিক অভিযোগ পত্ৰ প্ৰস্তুত কৰক।',
    rightsCardTitle: 'মোৰ অধিকাৰ',
    rightsCardDesc: 'সদস্য হিচাপে আপোনাৰ বিধিসন্মত অধিকাৰসমূহ বুজক।',
    voiceCardTitle: 'ভইচ সহায়ক',
    voiceCardDesc: 'অসমীয়াত কথা কৈ সহায় লাভ কৰক।',
    knowledgeCardTitle: 'নথি আৰু উৎস',
    knowledgeCardDesc: 'সমবায় আইন আৰু উপ-নিয়মসমূহ নিৰীক্ষণ কৰক।',
    activeWorkflowNotice: 'আপোনাৰ এটা আধৰুৱা কাম চলি আছে',
    resumeTaskBtn: 'কাম অব্যাহত ৰাখক',
    sampleQuestionsLabel: 'সঘনাই সোধা প্ৰশ্নসমূহ:',
    typePlaceholder: 'অসমীয়াত সোধক (যেনে: মই নিৰ্বাচনত ভোট দিব পাৰিমনে?)...',
    sendBtn: 'প্ৰেৰণ কৰক',
    voiceBtn: 'কওক',
    clearChatBtn: 'চেট মচক',
    sourcesLabel: 'প্ৰমাণিত আইনী উৎস',
    demoDataBadge: 'ডেমো জ্ঞান ভাণ্ডাৰ',
    disclaimerText: 'জাননী: এই সহায়কে সমবায় উপ-নিয়মৰ ভিত্তিত তথ্য প্ৰদান কৰে। ই আইনী পৰামৰ্শৰ বিকল্প নহয়।',
    closeBtn: 'বন্ধ কৰক',
    backBtn: 'উভতি যাওক',
    continueBtn: 'আগবাঢ়ক',
    cancelBtn: 'বাতিল কৰক',
    saveBtn: 'সংৰক্ষণ কৰক',
    editBtn: 'সম্পাদনা কৰক',
    downloadPdfBtn: 'PDF ডাউনল\'ড',
    downloadTxtBtn: 'TXT ডাউনল\'ড',
    suggestedQ1: 'মই সমবায় সমিতিৰ নিৰ্বাচনত ভোট দিব পাৰিমনে?',
    suggestedQ2: 'সমবায় সদস্য হিচাপে মোৰ কি কি অধিকাৰ আছে?',
    suggestedQ3: 'পৰিচালনা সমিতিৰ বিৰুদ্ধে কেনেকৈ অভিযোগ কৰিব?',
    suggestedQ4: 'সমবায় সমিতি পঞ্জীয়নৰ বাবে কি কি নথি প্ৰয়োজন?',
    voiceListening: 'আপোনাৰ কথা শুনা হৈছে...',
    voiceProcessing: 'বুজি থকা হৈছে...',
    voiceSpeaking: 'অসমীয়াত উত্তৰ দিয়া হৈছে...',
    voiceIdle: 'ক\'বলৈ মাইক টিপক',
  },
};
